#!/usr/bin/env bash
set -u
ROOT="/root/trendforge-mvp/server"
ENV_FILE="/etc/trendforge-v6.env"
if [ -f "$ENV_FILE" ]; then
  set -a
  source "$ENV_FILE"
  set +a
fi
cd "$ROOT" || exit 1
echo "=== TrendForge V17 pipeline start: $(date -u +'%Y-%m-%dT%H:%M:%SZ') ==="
echo "[0/36] sql/migrate_v10.sql"
sqlite3 "${DB_PATH:-trendforge.db}" < "$ROOT/sql/migrate_v10.sql" || echo "WARN: migrate_v10.sql failed (continuing)"
echo "[1/36] sql/migrate_v11.sql"
sqlite3 "${DB_PATH:-trendforge.db}" < "$ROOT/sql/migrate_v11.sql" || echo "WARN: migrate_v11.sql failed (continuing)"
echo "[2/36] sql/migrate_v12.sql"
sqlite3 "${DB_PATH:-trendforge.db}" < "$ROOT/sql/migrate_v12.sql" || echo "WARN: migrate_v12.sql failed (continuing)"
echo "[3/36] sql/migrate_v13.sql"
sqlite3 "${DB_PATH:-trendforge.db}" < "$ROOT/sql/migrate_v13.sql" || echo "WARN: migrate_v13.sql failed (continuing)"
echo "[4/36] sql/migrate_v15.sql"
sqlite3 "${DB_PATH:-trendforge.db}" < "$ROOT/sql/migrate_v15.sql" || echo "WARN: migrate_v15.sql failed (continuing)"
echo "[5/36] sql/migrate_v16.sql"
sqlite3 "${DB_PATH:-trendforge.db}" < "$ROOT/sql/migrate_v16.sql" || echo "WARN: migrate_v16.sql failed (continuing)"
echo "[6/36] sources/fetch_google_trends_serpapi.py"
python3 "$ROOT/sources/fetch_google_trends_serpapi.py" || echo "WARN: fetch_google_trends_serpapi.py failed (continuing)"
echo "[7/36] sources/fetch_etsy_pod_v3.py"
python3 "$ROOT/sources/fetch_etsy_pod_v3.py" || echo "WARN: fetch_etsy_pod_v3.py failed (continuing)"
echo "[8/36] sources/fetch_amazon_pod_terms_v2.py"
python3 "$ROOT/sources/fetch_amazon_pod_terms_v2.py" || echo "WARN: fetch_amazon_pod_terms_v2.py failed (continuing)"
echo "[9/36] sources/fetch_tiktok_pod_trends_v1.py"
python3 "$ROOT/sources/fetch_tiktok_pod_trends_v1.py" || echo "WARN: fetch_tiktok_pod_trends_v1.py failed (continuing)"
echo "[10/36] sources/fetch_reddit_trends_v1.py"
python3 "$ROOT/sources/fetch_reddit_trends_v1.py" || echo "WARN: fetch_reddit_trends_v1.py failed (continuing)"
echo "[11/36] sources/fetch_pinterest_trends_v1.py"
python3 "$ROOT/sources/fetch_pinterest_trends_v1.py" || echo "WARN: fetch_pinterest_trends_v1.py failed (continuing)"
echo "[12/36] engines/extract_pod_keywords.py"
python3 "$ROOT/engines/extract_pod_keywords.py" || echo "WARN: extract_pod_keywords.py failed (continuing)"
echo "[13/36] engines/build_trends_from_raw.py"
python3 "$ROOT/engines/build_trends_from_raw.py" || echo "WARN: build_trends_from_raw.py failed (continuing)"
echo "[14/36] engines/pod_relevance_filter_v1.py"
python3 "$ROOT/engines/pod_relevance_filter_v1.py" || echo "WARN: pod_relevance_filter_v1.py failed (continuing)"
echo "[15/36] engines/trend_expansion_engine_v2.py"
python3 "$ROOT/engines/trend_expansion_engine_v2.py" || echo "WARN: trend_expansion_engine_v2.py failed (continuing)"
echo "[16/36] engines/design_concept_engine.py"
python3 "$ROOT/engines/design_concept_engine.py" || echo "WARN: design_concept_engine.py failed (continuing)"
echo "[17/36] engines/mj_prompt_generator.py"
python3 "$ROOT/engines/mj_prompt_generator.py" || echo "WARN: mj_prompt_generator.py failed (continuing)"
echo "[18/36] engines/sku_pack_engine.py"
python3 "$ROOT/engines/sku_pack_engine.py" || echo "WARN: sku_pack_engine.py failed (continuing)"
echo "[19/36] engines/listing_generator.py"
python3 "$ROOT/engines/listing_generator.py" || echo "WARN: listing_generator.py failed (continuing)"
echo "[20/36] engines/listing_seo_engine.py"
python3 "$ROOT/engines/listing_seo_engine.py" || echo "WARN: listing_seo_engine.py failed (continuing)"
echo "[21/36] engines/listing_quality_engine.py"
python3 "$ROOT/engines/listing_quality_engine.py" || echo "WARN: listing_quality_engine.py failed (continuing)"
echo "[22/36] engines/listing_ranker.py"
python3 "$ROOT/engines/listing_ranker.py" || echo "WARN: listing_ranker.py failed (continuing)"
echo "[23/36] engines/niche_finder_engine.py"
python3 "$ROOT/engines/niche_finder_engine.py" || echo "WARN: niche_finder_engine.py failed (continuing)"
echo "[24/36] engines/market_gap_detector.py"
python3 "$ROOT/engines/market_gap_detector.py" || echo "WARN: market_gap_detector.py failed (continuing)"
echo "[25/36] engines/profit_score_engine.py"
python3 "$ROOT/engines/profit_score_engine.py" || echo "WARN: profit_score_engine.py failed (continuing)"
echo "[26/36] engines/execution_pack_engine.py"
python3 "$ROOT/engines/execution_pack_engine.py" || echo "WARN: execution_pack_engine.py failed (continuing)"
echo "[27/36] engines/seller_workspace_engine.py"
python3 "$ROOT/engines/seller_workspace_engine.py" || echo "WARN: seller_workspace_engine.py failed (continuing)"
echo "[28/36] engines/seller_saved_trends_engine.py"
python3 "$ROOT/engines/seller_saved_trends_engine.py" || echo "WARN: seller_saved_trends_engine.py failed (continuing)"
echo "[29/36] engines/amazon_listing_generator_v1.py"
python3 "$ROOT/engines/amazon_listing_generator_v1.py" || echo "WARN: amazon_listing_generator_v1.py failed (continuing)"
echo "[30/36] api/dashboard_api.py"
python3 "$ROOT/api/dashboard_api.py" || echo "WARN: dashboard_api.py failed (continuing)"
echo "[31/36] api/execution_pack_viewer.py"
python3 "$ROOT/api/execution_pack_viewer.py" || echo "WARN: execution_pack_viewer.py failed (continuing)"
echo "[32/36] api/top_trend_board.py"
python3 "$ROOT/api/top_trend_board.py" || echo "WARN: top_trend_board.py failed (continuing)"
echo "[33/36] api/seller_api.py"
python3 "$ROOT/api/seller_api.py" || echo "WARN: seller_api.py failed (continuing)"
echo "[34/36] api/seller_dashboard_api.py"
python3 "$ROOT/api/seller_dashboard_api.py" || echo "WARN: seller_dashboard_api.py failed (continuing)"
echo "[35/36] push/push_trends_feishu_v711.py"
python3 "$ROOT/push/push_trends_feishu_v711.py" || echo "WARN: push_trends_feishu_v711.py failed (continuing)"
echo "=== TrendForge V17 pipeline end:   $(date -u +'%Y-%m-%dT%H:%M:%SZ') ==="
