#!/usr/bin/env bash
set -u
ROOT="/root/trendforge-mvp/server"
ENV_FILE="/etc/trendforge-v6.env"
if [ -f "$ENV_FILE" ]; then
  set -a
  source "$ENV_FILE"
  set +a
fi
cd "$ROOT" || exit 1
echo "=== TrendForge V12 pipeline start: $(date -u +'%Y-%m-%dT%H:%M:%SZ') ==="
echo "[0/21] sql/migrate_v10.sql"
sqlite3 "${DB_PATH:-trendforge.db}" < "$ROOT/sql/migrate_v10.sql" || echo "WARN: migrate_v10.sql failed (continuing)"
echo "[1/21] sql/migrate_v11.sql"
sqlite3 "${DB_PATH:-trendforge.db}" < "$ROOT/sql/migrate_v11.sql" || echo "WARN: migrate_v11.sql failed (continuing)"
echo "[2/21] sql/migrate_v12.sql"
sqlite3 "${DB_PATH:-trendforge.db}" < "$ROOT/sql/migrate_v12.sql" || echo "WARN: migrate_v12.sql failed (continuing)"
echo "[3/21] sources/fetch_google_trends_serpapi.py"
python3 "$ROOT/sources/fetch_google_trends_serpapi.py" || echo "WARN: fetch_google_trends_serpapi.py failed (continuing)"
echo "[4/21] sources/fetch_etsy_pod_v2.py"
python3 "$ROOT/sources/fetch_etsy_pod_v2.py" || echo "WARN: fetch_etsy_pod_v2.py failed (continuing)"
echo "[5/21] sources/fetch_amazon_pod_terms_v2.py"
python3 "$ROOT/sources/fetch_amazon_pod_terms_v2.py" || echo "WARN: fetch_amazon_pod_terms_v2.py failed (continuing)"
echo "[6/21] sources/fetch_tiktok_pod_trends_v1.py"
python3 "$ROOT/sources/fetch_tiktok_pod_trends_v1.py" || echo "WARN: fetch_tiktok_pod_trends_v1.py failed (continuing)"
echo "[7/21] engines/extract_pod_keywords.py"
python3 "$ROOT/engines/extract_pod_keywords.py" || echo "WARN: extract_pod_keywords.py failed (continuing)"
echo "[8/21] engines/build_trends_from_raw.py"
python3 "$ROOT/engines/build_trends_from_raw.py" || echo "WARN: build_trends_from_raw.py failed (continuing)"
echo "[9/21] engines/trend_expansion_engine_v2.py"
python3 "$ROOT/engines/trend_expansion_engine_v2.py" || echo "WARN: trend_expansion_engine_v2.py failed (continuing)"
echo "[10/21] engines/design_concept_engine.py"
python3 "$ROOT/engines/design_concept_engine.py" || echo "WARN: design_concept_engine.py failed (continuing)"
echo "[11/21] engines/mj_prompt_generator.py"
python3 "$ROOT/engines/mj_prompt_generator.py" || echo "WARN: mj_prompt_generator.py failed (continuing)"
echo "[12/21] engines/sku_pack_engine.py"
python3 "$ROOT/engines/sku_pack_engine.py" || echo "WARN: sku_pack_engine.py failed (continuing)"
echo "[13/21] engines/listing_generator.py"
python3 "$ROOT/engines/listing_generator.py" || echo "WARN: listing_generator.py failed (continuing)"
echo "[14/21] engines/listing_seo_engine.py"
python3 "$ROOT/engines/listing_seo_engine.py" || echo "WARN: listing_seo_engine.py failed (continuing)"
echo "[15/21] engines/listing_quality_engine.py"
python3 "$ROOT/engines/listing_quality_engine.py" || echo "WARN: listing_quality_engine.py failed (continuing)"
echo "[16/21] engines/listing_ranker.py"
python3 "$ROOT/engines/listing_ranker.py" || echo "WARN: listing_ranker.py failed (continuing)"
echo "[17/21] engines/niche_finder_engine.py"
python3 "$ROOT/engines/niche_finder_engine.py" || echo "WARN: niche_finder_engine.py failed (continuing)"
echo "[18/21] engines/market_gap_detector.py"
python3 "$ROOT/engines/market_gap_detector.py" || echo "WARN: market_gap_detector.py failed (continuing)"
echo "[19/21] engines/profit_score_engine.py"
python3 "$ROOT/engines/profit_score_engine.py" || echo "WARN: profit_score_engine.py failed (continuing)"
echo "[20/21] engines/execution_pack_engine.py"
python3 "$ROOT/engines/execution_pack_engine.py" || echo "WARN: execution_pack_engine.py failed (continuing)"
echo "[21/21] push/push_trends_feishu_v711.py"
python3 "$ROOT/push/push_trends_feishu_v711.py" || echo "WARN: push_trends_feishu_v711.py failed (continuing)"
echo "=== TrendForge V12 pipeline end:   $(date -u +'%Y-%m-%dT%H:%M:%SZ') ==="
