#!/usr/bin/env bash
set -u
ROOT="/root/trendforge-mvp/server"
ENV_FILE="/etc/trendforge-v6.env"
if [ -f "$ENV_FILE" ]; then
  set -a
  source "$ENV_FILE"
  set +a
fi
cd "$ROOT" || exit 1
echo "=== TrendForge V13 pipeline start: $(date -u +'%Y-%m-%dT%H:%M:%SZ') ==="
echo "[0/26] sql/migrate_v10.sql"
sqlite3 "${DB_PATH:-trendforge.db}" < "$ROOT/sql/migrate_v10.sql" || echo "WARN: migrate_v10.sql failed (continuing)"
echo "[1/26] sql/migrate_v11.sql"
sqlite3 "${DB_PATH:-trendforge.db}" < "$ROOT/sql/migrate_v11.sql" || echo "WARN: migrate_v11.sql failed (continuing)"
echo "[2/26] sql/migrate_v12.sql"
sqlite3 "${DB_PATH:-trendforge.db}" < "$ROOT/sql/migrate_v12.sql" || echo "WARN: migrate_v12.sql failed (continuing)"
echo "[3/26] sql/migrate_v13.sql"
sqlite3 "${DB_PATH:-trendforge.db}" < "$ROOT/sql/migrate_v13.sql" || echo "WARN: migrate_v13.sql failed (continuing)"
echo "[4/26] sources/fetch_google_trends_serpapi.py"
python3 "$ROOT/sources/fetch_google_trends_serpapi.py" || echo "WARN: fetch_google_trends_serpapi.py failed (continuing)"
echo "[5/26] sources/fetch_etsy_pod_v2.py"
python3 "$ROOT/sources/fetch_etsy_pod_v2.py" || echo "WARN: fetch_etsy_pod_v2.py failed (continuing)"
echo "[6/26] sources/fetch_amazon_pod_terms_v2.py"
python3 "$ROOT/sources/fetch_amazon_pod_terms_v2.py" || echo "WARN: fetch_amazon_pod_terms_v2.py failed (continuing)"
echo "[7/26] sources/fetch_tiktok_pod_trends_v1.py"
python3 "$ROOT/sources/fetch_tiktok_pod_trends_v1.py" || echo "WARN: fetch_tiktok_pod_trends_v1.py failed (continuing)"
echo "[8/26] engines/extract_pod_keywords.py"
python3 "$ROOT/engines/extract_pod_keywords.py" || echo "WARN: extract_pod_keywords.py failed (continuing)"
echo "[9/26] engines/build_trends_from_raw.py"
python3 "$ROOT/engines/build_trends_from_raw.py" || echo "WARN: build_trends_from_raw.py failed (continuing)"
echo "[10/26] engines/trend_expansion_engine_v2.py"
python3 "$ROOT/engines/trend_expansion_engine_v2.py" || echo "WARN: trend_expansion_engine_v2.py failed (continuing)"
echo "[11/26] engines/design_concept_engine.py"
python3 "$ROOT/engines/design_concept_engine.py" || echo "WARN: design_concept_engine.py failed (continuing)"
echo "[12/26] engines/mj_prompt_generator.py"
python3 "$ROOT/engines/mj_prompt_generator.py" || echo "WARN: mj_prompt_generator.py failed (continuing)"
echo "[13/26] engines/sku_pack_engine.py"
python3 "$ROOT/engines/sku_pack_engine.py" || echo "WARN: sku_pack_engine.py failed (continuing)"
echo "[14/26] engines/listing_generator.py"
python3 "$ROOT/engines/listing_generator.py" || echo "WARN: listing_generator.py failed (continuing)"
echo "[15/26] engines/listing_seo_engine.py"
python3 "$ROOT/engines/listing_seo_engine.py" || echo "WARN: listing_seo_engine.py failed (continuing)"
echo "[16/26] engines/listing_quality_engine.py"
python3 "$ROOT/engines/listing_quality_engine.py" || echo "WARN: listing_quality_engine.py failed (continuing)"
echo "[17/26] engines/listing_ranker.py"
python3 "$ROOT/engines/listing_ranker.py" || echo "WARN: listing_ranker.py failed (continuing)"
echo "[18/26] engines/niche_finder_engine.py"
python3 "$ROOT/engines/niche_finder_engine.py" || echo "WARN: niche_finder_engine.py failed (continuing)"
echo "[19/26] engines/market_gap_detector.py"
python3 "$ROOT/engines/market_gap_detector.py" || echo "WARN: market_gap_detector.py failed (continuing)"
echo "[20/26] engines/profit_score_engine.py"
python3 "$ROOT/engines/profit_score_engine.py" || echo "WARN: profit_score_engine.py failed (continuing)"
echo "[21/26] engines/execution_pack_engine.py"
python3 "$ROOT/engines/execution_pack_engine.py" || echo "WARN: execution_pack_engine.py failed (continuing)"
echo "[22/26] api/dashboard_api.py"
python3 "$ROOT/api/dashboard_api.py" || echo "WARN: dashboard_api.py failed (continuing)"
echo "[23/26] api/execution_pack_viewer.py"
python3 "$ROOT/api/execution_pack_viewer.py" || echo "WARN: execution_pack_viewer.py failed (continuing)"
echo "[24/26] api/top_trend_board.py"
python3 "$ROOT/api/top_trend_board.py" || echo "WARN: top_trend_board.py failed (continuing)"
echo "[25/26] push/push_trends_feishu_v711.py"
python3 "$ROOT/push/push_trends_feishu_v711.py" || echo "WARN: push_trends_feishu_v711.py failed (continuing)"
echo "=== TrendForge V13 pipeline end:   $(date -u +'%Y-%m-%dT%H:%M:%SZ') ==="
