-- TrendForge V79 AI Listing Engine
CREATE TABLE IF NOT EXISTS listing_ai_v79 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    release_command_id INTEGER,
    launch_control_id INTEGER,
    launch_orchestrator_id INTEGER,
    dispatch_center_id INTEGER,
    release_routing_id INTEGER,
    allocation_board_id INTEGER,
    portfolio_matrix_id INTEGER,
    executive_grid_id INTEGER,
    strategic_hub_id INTEGER,
    operations_hq_id INTEGER,
    war_room_id INTEGER,
    control_tower_id INTEGER,
    mission_planner_id INTEGER,
    batch_studio_id INTEGER,
    command_center_id INTEGER,
    ops_dashboard_id INTEGER,
    publish_board_id INTEGER,
    launch_queue_id INTEGER,
    execution_pack_id INTEGER,
    listing_id INTEGER,
    source_term TEXT,
    safe_term TEXT,
    risk_level TEXT,
    product_type TEXT,
    priority_tier TEXT,
    title_en TEXT,
    tags_text TEXT,
    bullets_text TEXT,
    description_text TEXT,
    design_prompt TEXT,
    mockup_prompt TEXT,
    sku_code TEXT,
    listing_score REAL DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_listing_ai_v79_product ON listing_ai_v79(product_type);
CREATE INDEX IF NOT EXISTS idx_listing_ai_v79_score ON listing_ai_v79(listing_score DESC);
